services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: my_fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=fastapi  # Ustaw hasło zgodne z MYSQL_ROOT_PASSWORD w db
      - MYSQL_DB=training_db
      - MYSQL_HOST=db
      - DATABASE_URL=mysql+mysqldb://root:fastapi@db:3306/training_db
    volumes:
      - .:/app
    # restart: always  # <- w production można ustawić

  db:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=fastapi  # Ustaw hasło dla root
      - MYSQL_DATABASE=training_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  mysql_data: