services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: my_fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=fastapi
      - MYSQL_DB=training_db
      - MYSQL_HOST=db
      - DATABASE_URL=mysql+mysqldb://root:fastapi@db:3306/training_db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=fastapi
      - MYSQL_DATABASE=training_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pfastapi", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

volumes:
  mysql_data:
